### ISSUE TITLE
Missing views in JSON since stucturizr-lite upgrade to structurizr-* 2.1.0

### ISSUE THREAD

**Issue by beffge** [structurizr/examples#15]
### Description

A JSON workspace with multiple views defined gets read by structurizr/lite, changed and written back to file with all views missing.

### Steps to reproduce

1. Take the example from [here](https://www.structurizr.com/json?example=big-bank-plc).
2. Duplicate a view e.g. SystemContext and rename only the key.
3. Store workspace.json locally and accessible by structurizr/lite
4. Start structurizr/lite with the folder mounted to the one where the workspace.json is stored
5. View structurizr/lite in the browser (one view missing)
6. Check workspace.json e.g. lastModifiedAgent == structurizr-javascript and systemContextViews array has only one view

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
What is it you're actually trying to do here?

**Comment by beffge** [comment]
I edit the JSON via tooling and now the views are disappearing 😅

**Comment by simonbrowndotje** [comment]
I've removed those examples, but changing `key` and `order` (to make them both unique) works for me.

**Comment by beffge** [comment]
You're right, I guess I made a copy paste mistake.

**Comment by simonbrowndotje** [comment]
I've added a note to the JSON repo about the need for `order` to also be unique -> https://github.com/structurizr/json?tab=readme-ov-file#workspace-validation-rules
