### ISSUE TITLE
Custom view DSL examples

### ISSUE THREAD

**Issue by roganov** [structurizr/examples#16]
### Description

Hello

I was trying to understand how Custom Views work and their capabilities, but I can't find any examples.
There are two documentation pages:
1. [This page](https://docs.structurizr.com/ui/diagrams/custom-view) has an example of a rendered diagram, but not the source code.
2. [DSL Reference](https://docs.structurizr.com/dsl/language#custom-view) is also very terse and does not have examples.

Would it be possible to add this to the documentation?

### Priority

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
Examples have been added to the DSL cookbook:

- [Custom elements](https://docs.structurizr.com/dsl/cookbook/custom-elements/)
- [Custom views](https://docs.structurizr.com/dsl/cookbook/custom-view)
